### ISSUE TITLE
Unable to locate publishable resources  publishing complete

### ISSUE THREAD

**Issue by Jobin-Jas** [spatie/laravel-stripe-webhooks#103]
Getting Unable to locate publishable resources   error in Laravel v8 `php artisan vendor:publish --provider="Spatie\WebhookClient\WebhookClientServiceProvider" --tag="webhook-client-migrations"
 `

**Comment by Jobin-Jas** [comment]
Fixed  by running 👍 
`php artisan vendor:publish`
Select what you want to publish by giving the index number.
 here : `Spatie\WebhookClient\WebhookClientServiceProvider`

**Comment by Kaos-Industries** [comment]
> Fixed by running 👍 `php artisan vendor:publish` Select what you want to publish by giving the index number. here : `Spatie\WebhookClient\WebhookClientServiceProvider`

So the command you ran was `php artisan vendor:publish Spatie\WebhookClient\WebhookClientServiceProvider`, or something else? Either way I'm getting the same error and the docs should be updated to reflect whatever the new command is.
