### ISSUE TITLE
Is 3D Secure supported?

### ISSUE THREAD

**Issue by Kaos-Industries** [spatie/laravel-stripe-webhooks#111]
I have everything else set up and working as [described in full here](https://stackoverflow.com/questions/71411952/database-query-returns-null-for-3d-secure-payments?noredirect=1#comment126232209_71411952), and the webhooks fire as expected *except* when testing with the [3D secure test cards here](https://stripe.com/docs/testing#regulatory-cards) - in this case the database query returns null. Before I start looking for the issue elsewhere, can I clarify whether this package has been updated to handle 3D Secure?

**Comment by freekmurze** [comment]
This package can handle all incoming events from Stripe.
