### ISSUE TITLE
Typo in StripeWebhooksController 2.6.2

### ISSUE THREAD

**Issue by BoiteBeet** [spatie/laravel-stripe-webhooks#136]
In the version 2.6.2 of StripeWebhooksController at line 22:
`'webhook_model' => config('strip-webhooks.model', WebhookCall::class),`
Should be:
`'webhook_model' => config('stripe-webhooks.model', WebhookCall::class),`

**Comment by freekmurze** [comment]
Seems fine in the latest version: https://github.com/spatie/laravel-stripe-webhooks/blob/e905669362231c0aab52ac934ac3b40783a228bb/src/StripeWebhooksController.php#L21

Feel free to open up a PR should I be mistaken.

**Comment by BoiteBeet** [comment]
Last version is for PHP 8. Not compatible with existing PHP 7.4 projects.
