### ISSUE TITLE
 Does it support webhooks for Stripe Connect?

### ISSUE THREAD

**Issue by Xationch** [spatie/laravel-stripe-webhooks#23]
Hello,

First, I want to thank you for your different packages. It helps me a lot as a freelancer.

I'm also using Stripe Connect but I do not see the option to add the secret key to use the webhook with Connect. It's a missing feature?

thank you

**Comment by freekmurze** [comment]
I have not used Stripe Connect before, so that's why it's not in the package. I'd accept a fully documented and tested, non-breaking PR that adds this to the package.

**Comment by Xationch** [comment]
@freekmurze There is only the secret that change and the route for stripe inside the dashboard.

I'm sorry I clearly don't have the level in programming. I'll try to help a little (My actual exemple is taken from laracast tutorial) :

Routes
```
Route::group(['prefix' => 'webhook'], function () {
	Route::post('account', 'Webhooks\GatewayController@handleAccount');
	Route::post('connect', 'Webhooks\GatewayController@handleConnect');
});
```

GatewayController
```
	public function handleAccount()
	{
		$endpoint_secret = "whsec_XXX";
		$this->handle($endpoint_secret);
	}

	public function handleConnect()
	{
		$endpoint_secret = "whsec_YYY";
		$this->handle($endpoint_secret);
	}

	protected function handle($endpoint_secret)
	{
		$payload    = @file_get_contents("php://input");
		$sig_header = $_SERVER["HTTP_STRIPE_SIGNATURE"];
		$event      = null;

		try {
			$event = Webhook::constructEvent(
				$payload, $sig_header, $endpoint_secret
				);
		} catch(UnexpectedValueException $e) {
			http_response_code(400);
			exit();
		} catch(StripeErrorSignatureVerification $e) {
			http_response_code(400);
			exit();
		}

		$method = $this->eventToMethod($event['type']);

		if (method_exists($this, $method)) {
			$this->$method($event);
		}

		http_response_code(200);
	}
```
