### ISSUE TITLE
Programmatically (dis)allow signing secret verification

### ISSUE THREAD

**Issue by sylouuu** [spatie/laravel-stripe-webhooks#24]
Hello,

If few cases you may want to bypass the signature validation, as it's optional.

It could be nice to set it to true/false depending on environment for example.

What do you think about it?

Best

**Comment by freekmurze** [comment]
Can you give an concrete example of a situation where you want to skip the signing secret verification?

**Comment by sylouuu** [comment]
In testing environment you may want to skip this verification?

Just apply the middleware in staging and production.

In a local env you also have to deal with `valet share` and `ngrok` with unsupported SSL. So sending test webhooks from Stripe may be a little pain. In my case I use Postman to reach my webhook endpoint, but the signature verification stops me.

An option to apply the middleware based on a boolean (default `true`) would do the job.

Best

**Comment by freekmurze** [comment]
You can set a non-https url in the Stripe dashboard.

**Comment by adriandmitroca** [comment]
@sylouuu 

Have you figured it out how to pass signature verification in your tests?

**Comment by sylouuu** [comment]
@adriandmitroca Finally I didn't use this package. I've added myself a signature verification in production only.

**Comment by adriandmitroca** [comment]
That's good to know, thanks. Anyway, if someone else will struggle with this in the future, my idea is to execute jobs separately in the tests to verify expected results.

There's no real need to test it any level higher, as those stuff is covered by package tests.

**Comment by pierrocknroll** [comment]
I found a dirty solution for this...

Instead of using  ```Route::stripeWebhooks('stripe/webhook');```
Use your own controller : ```Route::post('stripe/webhook', 'WebhookController');```

Then override the __construct method to use the VerifySignature middleware when you want :
```php
use Spatie\StripeWebhooks\Middlewares\VerifySignature;
use Spatie\StripeWebhooks\StripeWebhooksController;

class WebhookController extends StripeWebhooksController
{
    public function __construct()
    {
        if (!in_array(app()->environment(), ['testing', 'local'])) {
            $this->middleware(VerifySignature::class);
        }
    }
}
```

**Comment by tyteck** [comment]
in fact you alrady have what you need.
in `spatie/laravel-stripe-webhooks/src/StripeSignatureValidator.php` you have 
```
class StripeSignatureValidator implements SignatureValidator
{
    public function isValid(Request $request, WebhookConfig $config): bool
    {
        if (! config('stripe-webhooks.verify_signature')) {
            return true;
        }
        ...
    }
}
```
seems to me all you need to do is set `config(['stripe-webhooks.verify_signature' => false]);` before running your test.
