### ISSUE TITLE
Support for Multiple Signing Secrets?

### ISSUE THREAD

**Issue by zschuessler** [spatie/laravel-stripe-webhooks#25]
Hi there, great package!

I see the signing secret is put into the config as a single key/value. What if we have multiple signing secrets for multiple environments and endpoints? Looks like config only supports a single signing key.

I _could_ workaround this by extending, but would rather not.

**Comment by freekmurze** [comment]
I'd accept a fully tested, backwards compatible PR that adds this to the package.

**Comment by FredWillson** [comment]
Has anyone does this yet? Connected accounts use a separate webhook, and different Signing Secret.

**Comment by phil-gibson** [comment]
Done! Thanks @freekmurze <3
