### ISSUE TITLE
Rejecting a webhook

### ISSUE THREAD

**Issue by mbuk** [spatie/laravel-stripe-webhooks#27]
Hi

I might be missing something really obvious here but I hit on this yesterday.

When testing I was occasionally receiving webhooks out of sequence from stripe. Eg: a subscription.updated hook came before the subscription.created.

Normally I’d deal with that by sending a non 200 response to stripe on the updated hook and that would cause it to retry again later, typically after the creation book has been received.

What’s the best way forward with this package to implement the same behaviour?

**Comment by freekmurze** [comment]
I'm thinking if you aren't queueing the work, you can just call abort inside an event or job.

**Comment by mbuk** [comment]
Doh! Perfect - I knew I was missing the obvious.
