### ISSUE TITLE
Webhook URL when using with Cashier

### ISSUE THREAD

**Issue by ronnievisser** [spatie/laravel-stripe-webhooks#29]
Hi,

I know in the readme it states that this package works with cashier. I believe then it should also work with Spark 6, right?

I have a question regarding the webhook url. Can it be the same as cashier/spark uses? or do we have to define a different one and only allow for the events cashier does not handle?

thanks

**Comment by freekmurze** [comment]
I don't know for sure. Test it out and report back here.

**Comment by ronnievisser** [comment]
Ok! Will do

**Comment by tshafer** [comment]
The answer is no, you need to define two separate routes. Other than that it works fine.
