### ISSUE TITLE
Exception after upgrading Stripe from 2018-08-23 to 2018-09-06

### ISSUE THREAD

**Issue by NSpehler** [spatie/laravel-stripe-webhooks#35]
Hello,

Immediately after upgrading my Stripe API version from 2018-08-23 to 2018-09-06, I started getting the following exception in my Laravel app:

`The signature t=1536815026,v1=XXXXXXXXx found in the header named Stripe-Signature is invalid. Make sure that the services.stripe.webhook_signing_secret config key is set to the value you found on the Stripe dashboard. If you are caching your config try running php artisan cache:clear to resolve the problem.`

Of course I tried `php artisan cache:clear`, without luck. I also verified the webhook signing secret in my Stripe dashboard and it seems to be correct.

Is there something specific to do when upgrading the Stripe API version?

Thanks,
Nicolas

**Comment by freekmurze** [comment]
I haven't upgrade the API in any of my projects and probably I won't to do this in the near feature.

I'd appreciate you (or someone else that use the latest API) to dig a little bit deeper in the problem and create a PR that fixes this.

**Comment by drbyte** [comment]
I tested this by upgrading the API in my projects and have had no errors.

The upgrade docs don't suggest any reason for the above-reported error in conjunction with what this API step upgrade involves: https://stripe.com/docs/upgrades?since=2018-08-23#api-changelog

**Comment by NSpehler** [comment]
My bad, the error was caused by me messing up my live/test API keys.

It coincided exactly with the moment I upgraded my API version, because Stripe sent a webhook to let my app know the API version had changed.

Sorry for the inconvenience,
Nicolas
