### ISSUE TITLE
Not hitting job?

### ISSUE THREAD

**Issue by cloudwales** [spatie/laravel-stripe-webhooks#36]
Hi. I've installed the package and all works bar when i call a job to be fired on the webhook.

If i fire the `charge.succeeded` test in Stripe it hits the server and adds a entry into the database, but it completely bypasses the config.jobs 

```
use App\Jobs\StripeWebhooks\HandleFailedCharge;
use App\Jobs\StripeWebhooks\HandleSucceededCharge;

'jobs' => [
        // 'source_chargeable' => \App\Jobs\StripeWebhooks\HandleChargeableSource::class,
        'charge_failed' => HandleFailedCharge::class,
        'charge_succeeded' => HandleSucceededCharge::class,
    ],
```

The Succeeded charge job as a temporary thing should Log the id and return a response, but it doesnt do either:

```
<?php

namespace App\Jobs\StripeWebhooks;

use App\Models\Admin\Ledger;
use App\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;
use Mail;
use Spatie\StripeWebhooks\StripeWebhookCall;

class HandleSucceededCharge implements ShouldQueue
{
	use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

	/** @var \Spatie\StripeWebhooks\StripeWebhookCall */
	public $webhookCall;

	public function __construct(StripeWebhookCall $webhookCall)
	{
		$this->webhookCall = $webhookCall;
	}

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {

    	\Log::info('Charge Succeeded for - ' . $this->webhookCall->payload['data']['object']['id']);
    	$user_id = Ledger::where('transaction_id',$this->webhookCall->payload['data']['object']['id'])->pluck('user_id')->first();
    	$user = User::where('id', $user_id)->first();

    	Log::info($user);
    	return new Response('Payment Succeeded Success - ' . json_encode($payload['data']['object']['id'] ), 200);
    }
}
```

Any ideas ?

Cheers

**Comment by freekmurze** [comment]
[Our tests](https://github.com/spatie/laravel-stripe-webhooks/blob/master/tests/IntegrationTest.php) seem to indicate that this should be working. Could you submit a failing test?

**Comment by cloudwales** [comment]
Hi @freekmurze, thanks for your response.

 I get a 200 response on all the tests and it adds the entry into the database correctly, but it doesn't do the logic in the HandleSucceededCharge Job.  I don't get any failed tests nor anything in the log. It shows up in the database as a successful call. 

Cheers

**Comment by freekmurze** [comment]
This bit in our tests proves that in normal circumstances the right job should get called: https://github.com/spatie/laravel-stripe-webhooks/blob/master/tests/IntegrationTest.php#L55-L57

Could it be the case that you cached your config and added that job to the config afterwards?

Try running `php artisan config:clear`.

**Comment by cloudwales** [comment]
Not cached unfortunately. Heres a screenshot of the response from Stripe test.

<img width="906" alt="screenshot 2018-10-10 at 14 18 06" src="https://user-images.githubusercontent.com/5739133/46738963-5a2fa500-cc97-11e8-8c45-095feeff5fe6.png">

**Comment by freekmurze** [comment]
Can you submit a failing test for me to look at?

**Comment by cloudwales** [comment]
Never mind. I sorted it. I went back to cashier and I was missing `CASHIER_ENV=testing` in the .env file.

Thanks for your help

**Comment by Kaos-Industries** [comment]
After an annoying day of debugging this and several related issues, I finally found a fix to this, #41, #47 and probably some others. I wasted a few hours on this alone because nothing gets logged in Laravel's logs and specifying the format completely wrong returns a successful status code in the Stripe CLI.

The problem is the description of the job in `stripe-webhook.php`, the event needs to be completely delimited by underscores:

    'jobs' => [
        "payment_intent_succeeded" => \App\Jobs\StripeWebhooks\PaymentIntentSucceeded::class,
        // 'source_chargeable' => \App\Jobs\StripeWebhooks\HandleChargeableSource::class,
        // 'charge_failed' => \App\Jobs\StripeWebhooks\HandleFailedCharge::class,
    ],

**Comment by n4inz** [comment]
same, issue
how to solve this problem?
Please help me

**Comment by Wyatt-NAT** [comment]
same, issue
how to solve this problem?

I can see that I have a record in the database, however this package does not call Job to carry out extra action utilising payload.
