### ISSUE TITLE
Need Help on Laravel publishing

### ISSUE THREAD

**Issue by Nainabbas** [spatie/laravel-stripe-webhooks#39]
After running
` composer require spatie/laravel-stripe-webhooks` command i published it through ` php artisan vendor:publish --provider="Spatie\StripeWebhooks\StripeWebhooksServiceProvider" --tag="migrations"
` command but no migration related to this is genrsted nor any config file

**Comment by freekmurze** [comment]
Do you see the package in the list if you run `php artisan vendor:publish`?

**Comment by Nainabbas** [comment]
No its not there in list, but the package is there in vender spatie folder

**Comment by Nainabbas** [comment]
ok did it after running `package discover` i think my laravel version was old for that project
