### ISSUE TITLE
 Maximum execution time of 60+2 seconds exceeded

### ISSUE THREAD

**Issue by SenorWesley** [spatie/laravel-stripe-webhooks#40]
Hi!

I just installed your package and tried to get it up and running. When I did however, I started getting the following exception:

`Fatal error: Maximum execution time of 60+2 seconds exceeded (terminated) in /Users/WesleyIntranet/Projects/vetona/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 254`

This happens when I press the submit button on my form and try to create a stripe source. 

Is this a known issue or should I investigate further?

Thanks!

**Comment by freekmurze** [comment]
I'm thinking this error is unrelated to this package itself.

If you do find that our package is in error, feel free to PR a f!x.
