### ISSUE TITLE
Failed install on laravel 5.7.3 when trying to update to 1.2.0

### ISSUE THREAD

**Issue by ChielTimmermans** [spatie/laravel-stripe-webhooks#42]
Hello,
I'm trying to install version 1.2.0 on my laravel project (5.7.3) but it is giving me some errors. 
I've allready installed version 1.1.4 but when i try to update i get the following error.

`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-stripe-webhooks 1.2.0 -> satisfiable by spatie/laravel-stripe-webhooks[1.2.0].
    - Conclusion: remove laravel/framework v5.7.3
    - Conclusion: don't install laravel/framework v5.7.3
    - spatie/laravel-stripe-webhooks 1.2.0 requires illuminate/support ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev], illuminate/support[5.8.x-dev, v5.8.0, v5.8.2, v5.8.3, v5.8.4].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.3].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v5.7.3
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.7.3
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.7.3
    - don't install illuminate/support v5.8.3|don't install laravel/framework v5.7.3
    - don't install illuminate/support v5.8.4|don't install laravel/framework v5.7.3
    - Installation request for laravel/framework (locked at v5.7.3, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.3].
`

Is this a problem on my side or did the update break something?

Thanks,

**Comment by freekmurze** [comment]
Composer shouldn't pull in 1.2.0 because it isn't compatible with your project.

Either upgrade to Laravel 5.8 or keep using v1.1.4.
