### ISSUE TITLE
Jobs never called

### ISSUE THREAD

**Issue by huggy06** [spatie/laravel-stripe-webhooks#47]
Hi 

Here ismy config

 'jobs' => [
        // 'source_chargeable' => \App\Jobs\StripeWebhooks\HandleChargeableSource::class,
        // 'charge_failed' => \App\Jobs\StripeWebhooks\HandleFailedCharge::class,
        'invoice_payment_action_required' => \App\Jobs\StripeWebhooks\HandlePaymentActionRequiredInvoice::class,
        'invoice_payment_failed' => \App\Jobs\StripeWebhooks\HandlePaymentFailedInvoice::class
    ],

I can send webhook test from stripe. It seems to be ok and save in DB in table webhook_calls.

But The job never handle the event, any idea ?

**Comment by freekmurze** [comment]
This test proves that the package is working as intended: https://github.com/spatie/laravel-stripe-webhooks/blob/fcfe8414e90961d2e6119ec79dee8f9af264fd77/tests/StripeWebhookCallTest.php#L33-L39

Make sure you followed all installation steps. 

Maybe you've cached your config? Try running `php artisan config:clear`.

**Comment by huggy06** [comment]
Yes I run php artisan config:clear, always same problerm

**Comment by freekmurze** [comment]
Then I guess you'll have to go through the code yourself and putting some `dump` statements to figure out what is going wrong in your app.

**Comment by adriandmitroca** [comment]
Have you figured the issue? I suppose this can be tricky, because actual Stripe event is named `invoice.payment_failed` and there might be mismatch between `.` and `_`.
