### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by NSpehler** [spatie/laravel-stripe-webhooks#49]
Hello Spatie,

This package currently throws an error when installed on a fresh Laravel 6 application.

Would be awesome if you could update the package's requirements soon after Laravel 6 ships next week!

Thank you and all the best,
Nicolas

**Comment by ankurk91** [comment]
https://github.com/spatie/laravel-webhook-client

need to updated first

**Comment by riasvdv** [comment]
Released 2.2.0 with Laravel 6 support!
