### ISSUE TITLE
Payment intent listener not been fired

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [spatie/laravel-stripe-webhooks#51]
hi, i'm trying to manage a payment_intent.succeeded event... in my event listenet provider i have
```php
'stripe-webhooks::payment_intent.succeeded' => [
            'App\Listeners\SuccededSourceListener',
],
```
but my listenet is never fired... the webhook is correctly implemented, infact if i try with a Stripe WebHook test, the request is 200 with a json message ''ok''
any idea?

thanks a lot

**Comment by AlbertoSinigaglia** [comment]
well, seems like Stripe in the dashboard say that it has thrown a ''payment_intent_succeded'' event, but the event on the database is stored as ''charge.succeeded''...

**Comment by ChaTbiM** [comment]
is this still the case ? , I am not able to catch 'payment_intent.succeeded' as the event is not firing 
@AlbertoSinigaglia

**Comment by AlbertoSinigaglia** [comment]
@ChaTbiM hei there... i'm pretty sure i managed to make it work, though at this point i don't quite recall how🙄

**Comment by ChaTbiM** [comment]
man , it is frustrating and have to do it by tomorrow , I can do second webhook and catch it but not a pretty solution at all ! 
@AlbertoSinigaglia

**Comment by AlbertoSinigaglia** [comment]
@ChaTbiM i think i just went with the other event i've posted as reply years ago, but it's not better than a guess..

**Comment by ChaTbiM** [comment]
@AlbertoSinigaglia tried both not working as an event and as a job 
default job is not triggered also
