### ISSUE TITLE
Typed property Spatie\WebhookClient\ProcessWebhookJob::$webhookCall must be an instance of Spatie\WebhookClient\Models\WebhookCall

### ISSUE THREAD

**Issue by Jabirr** [spatie/laravel-stripe-webhooks#57]
So i keep getting this error when ever im trying make a source.charge
 
Typed property Spatie\WebhookClient\ProcessWebhookJob::$webhookCall must be an instance of Spatie\WebhookClient\Models\WebhookCall
I get this error when at the stripe dashboard.

I am using the 2.2.1 version since im still on laravel 5.8. But i have no idea what im doing wrong?

In my web.php i added the stripe-webhook
My config is as follow:
`<?php

return [

    'signing_secret' => env('STRIPE_WEBHOOK_SK'),

    'jobs' => [
        'source_chargeable' => \App\Jobs\StripeWebhooks\HandleChargeableSource::class,
        'charge_succeeded' => \App\Jobs\StripeWebhooks\HandleSucceededCharge::class,
    ],

    'model' => \Spatie\StripeWebhooks\ProcessStripeWebhookJob::class,
];
`

But it doesnt even hit on of these jobs, what am i missing?

**Comment by Jabirr** [comment]
It seems it breaks in WebhookProcessor.php line 63 where dispatch($job) gets fired, if i remove that and add dispatch(new HandleChargeableSource($webhookCall)) then it works...

**Comment by N3rdP1um23** [comment]
Hey!  I have the same issue also.  I'm using the Stripe CLI and tried your correction but that didn't help also....

**Comment by Jabirr** [comment]
It worked for me to downgrade to a earlier version. In the newer version they use public WebhookCall $webhookCall. Which is breaking for me. If i remove the WebhookCall and make is public $webhookCall; then it works fine

**Comment by freekmurze** [comment]
Feel free to PR a fix for this.
