### ISSUE TITLE
The signature is invalid when doing valet share and stripe cli

### ISSUE THREAD

**Issue by otherjohn** [spatie/laravel-stripe-webhooks#59]
Ok, I am not sure what I am missing but I get the signature is invalid on the cli test.
Here are my steps:
1. valet share mysite.test 
I get 
```
ngrok by @inconshreveable                                                                                                                                                                   (Ctrl+C to quit)

Session Status                online
Account                       John H (Plan: Free)
Version                       2.3.35
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://randomgunk.ngrok.io -> http://birdies.test:60
Forwarding                    https://randomgunk.ngrok.io -> http://birdies.test:60
```
2. start up `stripe listen --forward-to https://randomgunk.ngrok.io/api/v1/stripe`
```
Ready! Your webhook signing secret is whsec_MYSUPERSECRETKEY (^C to quit)
```
3. I add that key in my stripe-webhooks.php
```
'signing_secret' => 'whsec_MYSUPERSECRETKEY',
```
4. finally I push the stripe trigger
```
stripe trigger invoice.payment_failed
```
I get 500 errors for everything and ngrok reports:
```

    "class": "Spatie\\WebhookClient\\Exceptions\\WebhookFailed",
    "message": "The signature is invalid.",
    "code": 0,
    "file": "/Users/John/code/curriki-pledge/vendor/spatie/laravel-webhook-client/src/Exceptions/WebhookFailed.php:11",
```

Funny thing is - If I put https://randomgunk.ngrok.io/api/v1/stripe in stripe dashboard as the webhook and send a test (using the dashboard webkey) it comes back 200?

**Comment by w0rd-driven** [comment]
I was able to wire this up without the need of `valet share` or `ngrok` at all. I would use a command like `stripe listen --forward-to https://stripe-webhooks.test/hooks` where the URL is my local instance. The CLI, at least in these later versions, seems to be removing the need for a forwarding service like ngrok. Valet share is likely what you would want if you wired up a more concrete webhook pairing. I believe the limitation is the CLI forwarding only works for whatever is generated by the CLI like the `trigger` or `events resend` commands. I don't remember seeing any events come through the tunnel I didn't trigger explicitly through the CLI.

**Comment by colbymchenry** [comment]
Were you guys able to figure this out? I can't get mine webhooks to go through with Stripe CLI in local dev environment either. Same errors.

**Comment by desaintflorent** [comment]
I don't know about ngrok, but it's working well on my local environnement.
Using OSX, laravel 7, Valet share and the webhook signing secret generated by the cli

Notes : 
I'm not using an ssl endpoint
I'm using the api route not the web, and didn't added the route to VerifyCsrfToken Middleware

http://mydomain.test/api/stripe/webhook

**Comment by Singtah** [comment]
> Were you guys able to figure this out? I can't get mine webhooks to go through with Stripe CLI in local dev environment either. Same errors.

Same here, I do have the problem on local dev environment with webhook redirecting to my API. 
Set the custom CLI endpointSecret but always get invalide signature. `req.body` seems to be complete.

**Comment by Danon910** [comment]
You may need to define a new WEBHOOK_SIGNING_SECRET in app which the console gives after the stripe listen --forward-to command.

**Comment by Singtah** [comment]
> You may need to define a new WEBHOOK_SIGNING_SECRET in app which the console gives after the stripe listen --forward-to command.

Key was OK. The request was parsed before hitting the signature verification.
https://github.com/stripe/stripe-node/issues/341#issuecomment-497408492 solved the issue

**Comment by max-fletcher** [comment]
I am on the same boat as you guys seems.

**Comment by mokhosh** [comment]
Same here. Everything was ok in test mode with test keys, but as soon as I switched to production keys, all webhooks are failing with `The signature is invalid.`

@freekmurze Do you know how we can begin to troubleshoot this?
