### ISSUE TITLE
invoice.payment_succeeded

### ISSUE THREAD

**Issue by iShotFT** [spatie/laravel-stripe-webhooks#60]
Dear,

How do I handle an event that get's sent to the laravel-stripe-webhooks handler that contains an underscore in it's event type? (eg. `invoice.payment_succeeded`)

I have tried:
`'invoice.payment\_succeeded'    => \App\Jobs\StripeInvoicePaymentSucceeded::class,`
`'invoice.payment_succeeded'    => \App\Jobs\StripeInvoicePaymentSucceeded::class,`
`'invoice.paymentsucceeded'    => \App\Jobs\StripeInvoicePaymentSucceeded::class,`
`'invoice.paymentSucceeded'    => \App\Jobs\StripeInvoicePaymentSucceeded::class,`
All of the above seem to have failed to trigger the actual job so far. They do appear in the webhook_calls table though.

With kind regards,

Andries Verbanck

**Comment by freekmurze** [comment]
You can specify the event names in the config file

```
    /*
     * You can define the job that should be run when a certain webhook hits your application
     * here. The key is the name of the Stripe event type with the `.` replaced by a `_`.
     *
     * You can find a list of Stripe webhook types here:
     * https://stripe.com/docs/api#event_types.
     */
    'jobs' => [
         'source_chargeable' => \App\Jobs\StripeWebhooks\HandleChargeableSource::class,
         'charge_failed' => \App\Jobs\StripeWebhooks\HandleFailedCharge::class,
    ],
```

**Comment by iShotFT** [comment]
Hello @freekmurze,

Appreciate the reply but maybe I wasn't clear in my original message. So here is a second attempt:

There is an event on Stripe that gets sent that is called `invoice.payment_succeeded` (Notice the `_` character in the actual event name). Usually, we would replace the dots (`.`) with underscores (`_`) in the config file, like the working examples below:

```'customer_created'              => \App\Jobs\StripeCustomerCreated::class,
'checkout_session_completed'    => \App\Jobs\StripeCheckoutSessionCompleted::class,```

But the event type I'm trying to catch actually **has an underscore in the event name itself**. What approach should I take to escape this `_` and not have it be replaced by a `.` in the webhook handler?


With kind regards,

Andries Verbanck

**Comment by freekmurze** [comment]
You'll have to source dive a bit to know for sure.

What is the value of `$this->webhookCall->payload['type']` when a webhook comes in on this line?
https://github.com/spatie/laravel-stripe-webhooks/blob/master/src/ProcessStripeWebhookJob.php#L16

**Comment by iShotFT** [comment]
> You'll have to source dive a bit to know for sure.
> 
> What is the value of `$this->webhookCall->payload['type']` when a webhook comes in on this line?
> https://github.com/spatie/laravel-stripe-webhooks/blob/master/src/ProcessStripeWebhookJob.php#L16

```
L16: dd($this->webhookCall->payload['type']);
L17: event("stripe-webhooks::{$this->webhookCall->payload['type']}", $this->webhookCall);
```

Output through queue listener:

```
[2020-04-07 19:13:08][eHLXcVIb1G9XUATV8iOSEPEGw82SPygB] Processing: Spatie\StripeWebhooks\ProcessStripeWebhookJob
"invoice.payment_succeeded"
```

**Comment by freekmurze** [comment]
This make me think that `invoice.payment_succeeded` is the right event to configure. Make sure to run `php artisan clear:config` after changing the config.

To verify your changed config is really working you might your `config('stripe-webhooks')` in a tinker session.

**Comment by iShotFT** [comment]
Hello @freekmurze,

I did some further digging because I don't use event listeners but rather jobs to trigger when the webhooks hit. When I do this in the source code:

```
dd($this->determineJobClass($this->webhookCall->payload['type']));
$jobClass = $this->determineJobClass($this->webhookCall->payload['type']);
```

And I trigger a `invoice.payment_succeeded` from the Stripe dashboard (using ngrok for forwarding) I get the following in `php artisan queue:listen`:

```
[2020-04-07 19:39:47][nhvzcodAKcK2mANYFEaoH7bJ2KBqnmzV] Processing: Spatie\StripeWebhooks\ProcessStripeWebhookJob
""
```

When I trigger another event, for example `customer.created` I do get a good result:

```
[2020-04-07 19:41:53][UqGOEb8f5zU5qvHEHowYYVs2lKdzSGbL] Processing: Spatie\StripeWebhooks\ProcessStripeWebhookJob
"App\Jobs\StripeCustomerCreated"
```

So, me being me and using jobs instead of event listeners, the problem might lie in the `determineJobClass` function instead of the events that are triggered.

**Comment by jmnyarega** [comment]
> php artisan config:clear
