### ISSUE TITLE
PHP ^7.4 being used for spatie, but doesn't work with Laravel ^7.0.

### ISSUE THREAD

**Issue by colbymchenry** [spatie/laravel-stripe-webhooks#61]
`syntax error, unexpected '$url' (T_VARIABLE), expecting ',' or ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '$url' (T_VARIABLE), expecting ',' or ')' at /home/vagrant/code/beastlybot/vendor/spatie/laravel-webhook-client/src/WebhookClientServiceProvider.php:28)`

This is because you are using PHP 7.4  => functionality for short-handing functions. However, Laravel 7 doesn't seem tow ork with PHP 7.4, only ^7.2.

**Comment by freekmurze** [comment]
Please upgrade to PHP 7.4

**Comment by AngelinCalu** [comment]
I have encountered the exact same problem using PHP 7.4.6 :(

**Comment by laurenwilliams92** [comment]
Also having this problem and I have just installed 7.4

**Comment by vicandam** [comment]
Also encounter with php 7.3.23

**Comment by vmitchell85** [comment]
In case it helps anyone else... I encountered this error in Tinkerwell and it ended up being the php executable being used in Tinkerwell.

**Comment by WilliamHiggs** [comment]
This problem is still present on PHP 7.4.22

**Comment by MaxChew** [comment]
Problem still here in PHP 7.4.24 (cli) (built: Sep 26 2021 20:47:23)
