### ISSUE TITLE
Custom webhook_calls table

### ISSUE THREAD

**Issue by gabrielbidula** [spatie/laravel-stripe-webhooks#65]
Is it possible to customize the webhook_calls table to use another name/columns?
Thanks

**Comment by freekmurze** [comment]
You can specify a different model to use in the config file. Using a custom model you can change the table name and customise  anything you want. Changing column names might not be possible.

**Comment by iredmedia** [comment]
This seems to fail as the controller no longer respects the configured `webhook_model`

https://github.com/spatie/laravel-stripe-webhooks/blob/3d155273c14b8f1cab406d352070e8b5ed5b942d/src/StripeWebhooksController.php#L23

Am I missing something? :)
