### ISSUE TITLE
Configuring Webhook endpoint URL correctly - and disabling Cashier default

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-stripe-webhooks#66]
Once you set the webhooks URL, how do you disable the default Cashier URL of /stripe/webhook?

According to the [installation steps](https://github.com/spatie/laravel-stripe-webhooks#installation), you define your webhook APi endpoint like this:

In routes/web.php:
```
Route::stripeWebhooks('my_stripe_webhooks_endpoint');
```
In the VerifyCsrfToken middleware:
```
protected $except = [
    'my_stripe_webhooks_endpoint',
];
```

Now, when I use the stripe-cli (on localhost) and run stripe listen (and forward events to http://localhost:8000/my_stripe_webhooks_endpoint, as specified in the [Stripe docs](https://stripe.com/docs/stripe-cli/webhooks#forward-events), I see a 500 POST response. Why, and how do i turn it to a 200 response that Stripe needs to see?

```
^COneStepAtATime:kb_backend_apis_laravel$ stripe listen --forward-to http://localhost:8000/my_stripe_webhooks_endpoint
> Ready! Your webhook signing secret is whsec_ER94Uk56z5nlcKrD1OREbX2Q9e1LgEXg (^C to quit)
2020-05-11 17:33:48   --> payment_intent.created [evt_0Ghm46DXGF9cqh5pIZatClX2]
2020-05-11 17:33:48  <--  [500] POST http://localhost:8000/my_stripe_webhooks_endpoint [evt_0Ghm46DXGF9cqh5pIZatClX2]
2020-05-11 17:35:58   --> payment_intent.created [evt_0Ghm6DDXGF9cqh5pdW88RL1W]
2020-05-11 17:35:58  <--  [500] POST http://localhost:8000/my_stripe_webhooks_endpoint [evt_0Ghm6DDXGF9cqh5pdW88RL1W]
```

On the other hand, this (Default) Cashier webhook route: stripe/webhook is still enabled, and responds with a 200 status code! Logs below from performing the same operation, except I forward the webhook events to /stripe/webhook:

How can I disable this default Cashier route, and make the one I want to use return a 200 response?

```
^COneStepAtATime:kb_backend_apis_laravel $ stripe listen --forward-to http://localhost:8000/stripe/webhook
> Ready! Your webhook signing secret is whsec_Ex94Uk56z5nlcKrD1OREbXVQ9e1LgEXg (^C to quit)
2020-05-11 17:51:46   --> payment_method.attached [evt_0GhmLTDXGF9cqh5p67406apI]
2020-05-11 17:51:46  <--  [200] POST http://localhost:8000/stripe/webhook [evt_0GhmLTDXGF9cqh5p67406apI]
2020-05-11 17:51:50   --> customer.source.created [evt_0GhmLTDXGF9cqh5pUVdieeIT]
2020-05-11 17:51:50  <--  [200] POST http://localhost:8000/stripe/webhook [evt_0GhmLTDXGF9cqh5pUVdieeIT]

```

**Comment by freekmurze** [comment]
> How can I disable this default Cashier route,

That's a question you should pose at the cashier repo.

**Comment by connecteev** [comment]
Here's the answer for anyone looking:

1. To disable cashier's routes: 
Add ```Cashier::ignoreRoutes();``` in the boot method of your AppServiceProvider

2. To fix the 500 error:
If override the Stripe Webhook job to perform custom logic as specified in https://github.com/spatie/laravel-stripe-webhooks#performing-custom-logic
Use
```
use Spatie\StripeWebhooks\ProcessStripeWebhookJob;

class MyCustomStripeWebhookJob extends ProcessStripeWebhookJob
{
    public function handle()
    {
        // do some custom stuff beforehand

        parent::handle();

        // do some custom stuff afterwards
    }
}
```

You cannot have a __construct() function (which gets created by default if you run php artisan make:job) in this job, which will throw the 500 exception 
```
    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }
```

Exception:
```
[2020-05-12 17:08:26] local.ERROR: Typed property Spatie\WebhookClient\ProcessWebhookJob::$webhookCall must not be accessed before initialization {"exception":"[object] (Error(code: 0): Typed property Spatie\\WebhookClient\\ProcessWebhookJob::$webhookCall must not be accessed before initialization at 
```

**Comment by iKlsR** [comment]
Similar problem I guess, maybe I'm doing something wrong but in case it helps someone. I'm using Cashier which by default listens on `/stripe/webhook`. I have this configured in my stripe webhook dashboard to receive all events and I also have `Route::stripeWebhooks('/stripe/webhooks/charge/succeeded');` to only receive charges and in VerifyCsrfToken I just put `'stripe/*',`. My charges would pass but the main cashier url would return a 403 and my models would not get updated, the "fix" was using the *main* webhook's signing_secret in my .env and not the charges one.

**Comment by mmukhin** [comment]
> 1. Cashier::ignoreRoutes();

I had to put it in the `register` method (not `boot`) to get it to work. Ty though!
