### ISSUE TITLE
Job doesn't run

### ISSUE THREAD

**Issue by slower1337** [spatie/laravel-stripe-webhooks#69]
I've checked some issues about jobs and there is no answer that could solve the problem.

I did everything like in docs and Stripe CLI responses with 200 on every event, including charge.succeeded

Here is my **stripe-webhooks.php**:
![Screenshot from 2020-06-22 14-14-38](https://user-images.githubusercontent.com/47865427/85291784-d4678380-b492-11ea-8493-16e2b0090c41.png)

You may say: _"Clear the cache!"_, but I've already done it by running this: 
`php artisan cache:clear && php artisan route:clear && php artisan config:clear && php artisan view:clear && clear && php artisan serve`

As you can see it clears all the caches. But if you don't believe me, here is the proof from _tinker_:
![Screenshot from 2020-06-22 14-26-26](https://user-images.githubusercontent.com/47865427/85292850-6c19a180-b494-11ea-9e23-1e9c8e99c47a.png)

Here is the job (**HandleSucceededCharge.php** is located at **App/Jobs/StripeWebhooks**)
![Screenshot from 2020-06-22 14-18-41](https://user-images.githubusercontent.com/47865427/85292219-7ab38900-b493-11ea-8182-28750584bdbf.png)

I tried to insert `\Log::info('I am here, look!');`, but it doesn't log anything, anywhere.

If you need anything else to see, be kind to ask, thanks.

**Comment by freekmurze** [comment]
I don't see the error right away. Unfortunately I don't have time for debugging your specific project.

If you think the package is in error, please submit a failing test.

**Comment by slower1337** [comment]
It's a clean project...

**Comment by Hiranlive** [comment]
If you're running on stripe sandbox make sure to add these on your .env file.

    STRIPE_WEBHOOK_SECRET=xxxxxxxxxxxxxxxxx
    CASHIER_ENV=testing

**Comment by rpatechnologies** [comment]
@slower1337 Did you find any solution?  `CASHIER_ENV=testing` is not fixing this for me. The issue is reported many times but i think no genuine solutions exists till now?

**Comment by inagamov** [comment]
@rpatechnologies I think I figured that out. Try using this command: `php artisan queue:listen --timeout=0`
