### ISSUE TITLE
Signing Secret from Database

### ISSUE THREAD

**Issue by lovecoding-git** [spatie/laravel-stripe-webhooks#72]
Hi @freekmurze 

Thanks for such great package.

How can I use `signing_secret` from database field instead of from `.env` file?

**Comment by freekmurze** [comment]
In a service provider you could dynamically change the config file value.

```php
config()->set('stripe-webhooks.signing_secret', $anyValueYouWant);
```

**Comment by lovecoding-git** [comment]
OK, Thank you,
One question is this query (to get signing_secret value from database) will be executed every time on project?
Is there anyway to execute that query only when the webhook is working?
