### ISSUE TITLE
Getting signature is invalid error in Test mode

### ISSUE THREAD

**Issue by hrehman200** [spatie/laravel-stripe-webhooks#74]
Getting invalid signature error when triggering webhook call from Stripe dashboard. The signing_secret matches in both stripe dashboard and in code but still getting this issue all the time.

**Comment by colbymchenry** [comment]
Any updates to this? Seems in some projects it works fine. In others I get this error. For truly no valid reason that I can see.

**Comment by samargurjar** [comment]
Getting the same issue. any update or solution?

**Comment by hrehman200** [comment]
I had same issue. Had to comment out the signature check altogether.

**Comment by lnpbk** [comment]
I'm using this package for Stripe Connect, and I'm having the same issue

**Comment by chidt** [comment]
I have the same problem and I fixed it by change time on my server same as Stripe time because It check the timestamp when verifying an event's signatures. Hope it can have for you guys.
